# Configure main menu and social menu
#[[main]]
#identifier = "gallery"
#name = "Gallery"
#url = "/gallery/"
#[main.params]
#icon = "photo"
#newtab = true

#[[main]]
#identifier = "gallery"
#name = "Gallery"
#url = "/gallery/"
#weight = -90
#icon = "photo"

[[social]]
identifier = "github"
name = "GitHub"
url = "https://github.com/zzzqiii"

[social.params]
icon = "brand-github"

